export const ADD_COURSE = 'ADD_COURSE';
export const ADD_TIME = 'ADD_TIME';
export const REMOVE_ALL_COURSE = 'REMOVE_ALL_COURSE';
export const REPLACE_STATE = 'REPLACE_STATE';
export const TOGGLE_HEADER_COLORSET  = 'TOGGLE_HEADER_COLORSET';
